### ISSUE TITLE
Compilation error: no matching function for call to 'IRsend::begin(int, bool)'

### ISSUE THREAD

**Issue by CameraRick** [mattcuk/IRtranslator#1]
Hi there, thanks for this project, it's literally what I was searching for. This is also my first Arduino project ever, so I'm not yet able to help myself :(

I connected my Arduino Nano to the Arduino IDE, downloaded the IRremote lib (v4.1.2). When I opened up the irtranslator.ino and just try to push it to the Arduino (or verify for that matter), I receive the error `Compilation error: no matching function for call to 'IRsend::begin(int, bool)'`
I am a bit confused by that, because the command `IRsend` is nowhere to be found inside the .ino, only `IrSender`
Could that be an issue in the IRremote lib? I'm stuck at this step

Best Regards

**Comment by mattcuk** [comment]
Hi. The looks like it’d be due to the version of IRremote being waaay newer than the one I used at the time. In my screenshots that showed v3.5.2, so I’d recommend getting that version to see whether it fixes the problem for you.

Let me know how you get on 🙂

**Comment by CameraRick** [comment]
Hi there, thanks for getting back to me! I walked through the changelog of IRremote, and starting v4 they changed something with the IRsend command (I don't understand exactly what it is, but what gives). I tried up to v3.9 and that works :) hopefully I will now be able to properly set it up, one step at a time.

I want to integrate this into a little class D Amp I'm designing to use with my bedroom TV, it has IR but I couldn't "link" it to the remote. If this works, I want to design a little PCB to get everything tidy together (never designed a PCB before, but you have to start with something huh)

Thanks again :)

**Comment by mattcuk** [comment]
Brilliant! I’d love to know how you get on with your project (I’ve not designed a PCB before either).. good luck!

**Comment by bkcberry** [comment]
@CameraRick, did this work for you? I'm using v3.5.2 of the IRremote library but i'm getting the error below. All i've done is paste the code into the IDE and try to compile, haven't made any changes

`Compilation error: no matching function for call to 'IRsend::sendRaw(unsigned int [67], unsigned int, int)'`

**Comment by CameraRick** [comment]
@bkcberry when using v3.9 (and a lower version I can't exactly recall) it compiled on my end, but I didn't test any further yet. I wanted to advance in this project next weekend

**Comment by bkcberry** [comment]
Oh it's because I'm trying to compile for an 8266. It compiles fine for an arduino uno. Thanks
