### ISSUE TITLE
no reaction after uploading code

### ISSUE THREAD

**Issue by CameraRick** [mattcuk/IRtranslator#2]
Hi there,

me again :) I now had some time on my hands to play around with your creation. I was halted several hours because of uploading-issues, but I was able to fix them.

Anyway, I now got the code uploaded (no changes made yet) as well as the hardware laid out on a breadboard. When the upload is done (or the Arduino is rebooted), I get two comments on the Serial Monitor

```
Initialise IrSender on PIN 3
Initialise IrReceiver on PIN 2
```

So the first lines of the code work as intended. However, after that nothing is printed. I tried a few IR remotes that definitely work, but I don't get a code print like you did in [your video](https://youtu.be/rTCGy0bqljE?t=157) (timestamp added to link). I do get lots of updates as soon as I unplug the IR receiver (no reaction when the sender is unplugged):

```
Protocol=UNKNOWN Hash=0x0 1 bits received
uint16_t rawData[1] = {8630};  // Protocol=UNKNOWN Hash=0x0 1 bits received

Current sequence = X X X X 
```

- I did check the wiring and measured if power gets transmitted
- my COM port has a default baud rate of 9600 inside of Windows, I changed that to 115200 like in the code, but no change
- I re-checked if my IR receiver has a different polarity, but it's as intended and connected properly

As mentioned before, this is my first Arduino project and I am out of ideas. Do you have any? :)

Also, I hope you don't mind me saying this, your layout shown in _/images/boardDesign.png_ is very confusing and a bit bloated, but also wrong I'm afraid - the Sender is correct, but the Receiver is not. `+3.3V` needs to be on the right pin, middle should be `GND` and left go on `D2`. On _/images/boardPic.png_ it is correct. I am not so good with using Github, so I have no idea where else to put, but I did draw a simple layout that you can of course add to this repo in case you want to: 

![IRtranslatorLayout](https://github.com/mattcuk/IRtranslator/assets/22145913/519d4c20-9745-41da-90d8-3e920d6ee3e3)

Best Regards

**Comment by CameraRick** [comment]
... while in bed I did have one last idea what could be the culprit: while figuring out the wiring (and the mentioned upload issues) I plugged things in and out in a happy-go-lucky manner, and because I'm an idiot I did it while power was connected.

Seems I just grilled the receiver. I ordered some spares and tried a new one now, and look at that, it works :) Thanks again, sorry for wasting your time, haha

**Comment by mattcuk** [comment]
Not a problem; I was just about to start to look into this and was so pleased when I saw your last comment :) Hope it goes ok with the new parts!
